---
dependencies:
  about: ^2.0.1
  animate_do: ^2.0.0
  cached_network_image: ^3.1.0
  facebook_audience_network: ^1.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  date_format: ^2.0.3
  dio: ^4.0.0
  filesize: ^2.0.1
  firebase_analytics: ^8.3.0
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_html: ^2.1.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.6.0
  flutter_cache_manager: ^3.1.2
  flutter_local_notifications: ^8.1.1+1
  flutter_markdown: ^0.6.4
  html: ^0.15.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  get: ^4.2.4
  introduction_screen: ^2.1.0
  material_floating_search_bar: ^0.3.4
  package_info_plus: ^1.0.5
  path_provider: ^2.0.2
  pull_to_refresh: ^2.0.0
  search_choices: ^2.0.6
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  shimmer_image: ^0.0.2
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.9
  validators: ^3.0.0
  webview_flutter: ^2.0.12
description: A new Flutter project.
dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0<3.0.0'
flutter:
  assets:
    - assets/images/
    - assets/privacy_policy.md
    - assets/terms.md
    - assets/icons/
  uses-material-design: true
flutter_icons:
  android: launcher_icon
  image_path: assets/icons/logo.png
  ios: false
name: newsify
publish_to: none
version: 1.0.0+1