---
dependencies:
  cupertino_icons: ^1.0.3
  fluttertoast: ^8.0.7
  shimmer_image: ^0.0.2
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  search_choices: ^2.0.6
  flutter_blurhash: ^0.6.0
  transparent_image: ^2.0.0
  material_floating_search_bar: ^0.3.4
  get: ^4.2.4
  introduction_screen: ^2.1.0
  pull_to_refresh: ^2.0.0
  logger: ^1.0.0
  html: ^0.15.0
  animate_do: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_staggered_animations: ^1.0.0
  http: ^0.13.3
  url_launcher: ^6.0.9
  date_format: ^2.0.3
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
description: A new Flutter project.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0<3.0.0'
flutter:
  uses-material-design: true
  assets:
    - assets/images/

name: news_app_test
publish_to: none
version: 1.0.0+1